FROM node:22-alpine
WORKDIR /app

RUN npm install -g pnpm@latest-10

COPY package*.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
ARG VITE_API_URL=http://localhost:4000

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host"]